### PR TITLE
vx-linux: 5.5

### PR DESCRIPTION
**Pull request by zen0bit**
new version out

### CODE REVIEW

**Review by philclifford — CHANGES_REQUESTED** [review]
Better to use https://github.com/VX-Linux/main/releases
to dynamically determine available releases (or latest), and since hashes are now provided there they should be used.

**Comment by zen0bit** [comment]
hash done

not sure How to dynamically determine available releases

**Comment by philclifford** [comment]
try something like this:

```
wget -q https://github.com/VX-Linux/main/releases/latest -O- |grep -o -e 'releases/tag/[[:digit:]]\+\.[[:digit:]]\+'|head -1|cut -d/ -f3
```
or
```
wget -q https://github.com/VX-Linux/main/releases -O- |grep -o -e 'releases/tag/[[:digit:]]\+\.[[:digit:]]\+'|sort -ru |cut -d/ -f3
```
 in  `releases_vxlinux()`

**Comment by zen0bit** [comment]
vx

**Review by flexiondotorg — APPROVED** [review]

**Pull request merged**
