### PR TITLE
Add Slax

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by zen0bit** [comment]
Hashes not yet working!

I asked author for solution...

**Comment by Tomas-M** [comment]
sha1sum slax-64bit-11.6.0.iso
b3771211c4485fec2e4f2418b06125f3e53424c5  slax-64bit-11.6.0.iso

sha1sum slax-64bit-15.0.1.iso
4ec9dff930251fbae847a56b18d53505147faf84  slax-64bit-15.0.1.iso

**Comment by Tomas-M** [comment]
BTW new Slax release will be available in a week or two, so you may need to update soon, just FYI

**Comment by zen0bit** [comment]
> sha1sum slax-64bit-11.6.0.iso b3771211c4485fec2e4f2418b06125f3e53424c5 slax-64bit-11.6.0.iso
> 
> sha1sum slax-64bit-15.0.1.iso 4ec9dff930251fbae847a56b18d53505147faf84 slax-64bit-15.0.1.iso

slax-64bit-11.6.0.iso doesn't match b3771211c4485fec2e4f2418b06125f3e53424c5

Are you sure @Tomas-M?

**Comment by zen0bit** [comment]
slax

**Comment by zen0bit** [comment]
md5 sums solved

**Comment by Tomas-M** [comment]
Please note that version of Slax based on debian has been updated to 12.2.0 and it is not recommended to use 12.1.0 anymore (it has fatal bugs)
Similarly, Slax based on Slackware has been updated to 15.0.4 and it is not recommended to use older 15.0.2 or 15.0.3 anymore for the same reason.

**Comment by zen0bit** [comment]
Using only latest version now...

**Comment by zen0bit** [comment]
ready

**Comment by zen0bit** [comment]
continues in #892

**Pull request closed without merging**
