### PR TITLE
macOS Ventura support

### PR DESCRIPTION
**Pull request by Alexey336**

### CODE REVIEW

**Comment by Alexey336** [comment]
Don't bother with commit [86b897c](https://github.com/quickemu-project/quickemu/pull/679/commits/86b897ccc5fb2ab5ed5b8f17dcdbbe0fa87e70ad), it was just for testing

**Comment by flexiondotorg** [comment]
Please drop https://github.com/quickemu-project/quickemu/pull/679/commits/86b897ccc5fb2ab5ed5b8f17dcdbbe0fa87e70ad from the commits and force push :+1:

**Comment by marius851000** [comment]
*To drop a commit, you can use: `git rebase HEAD~3 -i` and then replace the `pick` on the line with the commit by `delete`. You will then need to force push with `git push --force`*

**Comment by Alexey336** [comment]
I brought back SMP variables and changed emulated video device to vmware-svga from OSX-KVM project

> _To drop a commit, you can use: `git rebase HEAD~3 -i` and then replace the `pick` on the line with the commit by `delete`. You will then need to force push with `git push --force`_

Sorry, I've made this changes directly from github editor since I have lot's of other changes with this project on my local machine and have little knowledge about how is git works

**Comment by flexiondotorg** [comment]
Thanks for your help @Alexey336 

Fixed via:

- https://github.com/quickemu-project/quickemu/commit/b938e9e9e83d6b9eafd4db3db3dbcf2bd3b43c50
- https://github.com/quickemu-project/quickemu/commit/3468c3a4d8b1dd2cc14a336179465a2d0dce7d4c

**Pull request closed without merging**
