### PR TITLE
🏗️ Lint PRs + OS pack 🦥 1

### LINKED ISSUE #921: easyos will not boot
#### Expected behaviour

Expect to be able to boot up into downloaded OS

#### Actual behaviour

System did not boot up and went looking for pixie boot

#### Steps to reproduce the behaviour

quickget easyos 5.6.4
quickemu --vm easyos-5.6.4.conf

#### Quickemu output

 quickget easyos 5.6.4
easyos-5.6.4/easy-5.6.4-amd64.img              100%[===================================================================================================>] 857.00M  23.9MB/s    in 36s
Making easyos-5.6.4.conf
Giving user execute permissions on easyos-5.6.4.conf,

    quickemu --vm easyos-5.6.4.conf
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.0
 - Host:     "Garuda Linux" running Linux 6.7 (rog1)
 - CPU:       13th Gen Intel(R) Core(TM) i9-13980HX
 - CPU VM:   1 Socket(s), 8 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     easyos-5.6.4/disk.qcow2 (16G)
             Looks unused, booting from easyos-5.6.4/easy-5.6.4-amd64.img
 - Boot ISO: easyos-5.6.4/easy-5.6.4-amd64.img
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-dabrown ~/Public
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "easyos-5.6.4/easyos-5.6.4-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:easyos-5.6.4/easyos-5.6.4-monitor.socket
 - Serial:   On host:  nc -U "easyos-5.6.4/easyos-5.6.4-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:easyos-5.6.4/easyos-5.6.4-serial.socket

 - Process:  Starting easyos-5.6.4.conf as easyos-5.6.4 (107859)

Screenshot_20240208_110119

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a

❯ lsb_release --all
LSB Version:    n/a
Distributor ID: Garuda
Description:    Garuda Linux
Release:        Soaring
Codename:       Spizaetus
❯ uname -a
Linux rog1 6.7.4-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:37 +0000 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by zen0bit**
### Included:
🏗️ Lint PRs
📦 Artix Linux - First time in #758 - 🚥
📦 Athena OS - in #750 - 🚥
📦 bazzite - in #797
📦 Big Linux Thanks to @ruscher - in #748
🛠 BlendOS releases on 1 line
📦 Chimera Linux - in #781
📦 Crunchbang++ - in #881
🚑 EasyOS fix and new releases - in #924 fix #921
🌀 EndeavourOS dynamic releases Thanks to @lj3954 - in #907
🛠 Gentoo livegui - in #905
📦 Guix - in #768
📦 Nitrux - in #873
📦 Parrot Security - in #893
📦 Primtux Thanks to @DaffyDuke - in #887
📦 Slax - in #761
📦 Slint - in #889
📦 Slitaz GNU/Linux - in #664 - 🚥 
📦 SparkyLinux - in #799
🛠 spiral rename
🛠 ️Zorin 17 - in #880

* picture legend
🚥 = Allready approved by @flexiondotorg
🏗️ = workflow
📦 = new OS
🛠 = changed OS
🚑 = fix bug
🌀 = dynamic parsing

### CODE REVIEW

**Comment by lj3954** [comment]
Once again, you need to test the changes you make. Echoing a variable with quotation marks preserves new lines and other special characters. The releases and editions functions are supposed to separate entries with spaces, not new lines. If you insist on "fixing" incorrect ShellCheck errors, you must replace new lines with spaces in another way, such as by piping the output to `tr '\n' ' '`Z

**Comment by DidierSpaier** [comment]
I remove " 14.2.1" at end of line 880 as this Slint release is no more supported, so won't receive security fixes any more.

**Comment by zen0bit** [comment]
> Once again, you need to test the changes you make. Echoing a variable with quotation marks preserves new lines and other special characters. The releases and editions functions are supposed to separate entries with spaces, not new lines. If you insist on "fixing" incorrect ShellCheck errors, you must replace new lines with spaces in another way, such as by piping the output to `tr '\n' ' '`.

I don't have to. I am creating github action to check for me, if I don't broke something 😉

**Comment by zen0bit** [comment]
> I recommend to remove " 14.2.1" at end of line 880 as this Slint release is no more supported, so won't receive security fixes any more.

Bit forgot, but done now...

**Comment by flexiondotorg** [comment]
Closed via #986

**Pull request closed without merging**
