### PR TITLE
Add SliTaz GNU/Linux

### PR DESCRIPTION
**Pull request by zen0bit**
[Slitaz GNU/Linux](https://www.slitaz.org)

initial working commit

will need some refactoring?

### CODE REVIEW

**Comment by zen0bit** [comment]
slitaz

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
Please rebase this one.

I will accept a rebased pr as this distro has been actively maintained for over 15 years and has distinctive features.

**Comment by zen0bit** [comment]
ready

> Please rebase this one.
> 
> I will accept a rebased pr as this distro has been actively maintained for over 15 years and has distinctive features.

ready

**Comment by zen0bit** [comment]
continues in #892

**Pull request closed without merging**
