### PR TITLE
Add Tiny Core Linux

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by zen0bit** [comment]
tinycore

**Review by flexiondotorg — APPROVED** [review]

**Comment by zen0bit** [comment]
done on mobile.
Hopefully nothing messed..

**Comment by flexiondotorg** [comment]
These commits need squahsing and the HoloISO reference removing.

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
Please remove the stray holoiso reference

**Review by flexiondotorg — APPROVED** [review]

**Pull request merged**
