### PR TITLE
next patch

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by zen0bit** [comment]
include in nextpatch
#292 
#322
#324
#342
#343
#344
#345

**Comment by zen0bit** [comment]
Included OSes

https://i2.paste.pics/FY3NK.png

**Comment by zen0bit** [comment]
Someone check it

Maybe I forgot something...

**Comment by flexiondotorg** [comment]
Closing this as many of the PRs have been merged.

**Pull request closed without merging**
