### PR TITLE
add disk health check

### PR DESCRIPTION
**Pull request by TuxVinyards**
Simple ultra quick test based on `qqX`  function  `check_disk_is_okay`  

Outputs & exits if disk has errors.   Otherwise null.

Checked against copy of recent disk with error problems.

quickemu-disk-check

### CODE REVIEW

**Review by zen0bit — CHANGES_REQUESTED** [review]
rebase
...
lgtm

**Comment by TuxVinyards** [comment]
Rebase seems to have gone awry.   Deleting and re-doing ...

**Review by TuxVinyards — COMMENTED** [review]
End result looks okay.  This end ...  :crossed_fingers:

**Comment by zen0bit** [comment]
Don't work for me 🤷‍♂️

**Comment by TuxVinyards** [comment]
> Don't work for me 🤷‍♂️

Just finishing up the qqX point release at the moment.

I'll redo it.

**Comment by zen0bit** [comment]
```
ERROR! disk.qcow2 has problems. Try qemu-img check --help.

qemu-img: Could not open 'alpine-latest/disk.qcow2': Could not open 'alpine-latest/disk.qcow2': No such file or directory```

**Comment by TuxVinyards** [comment]
> ```
> ERROR! disk.qcow2 has problems. Try qemu-img check --help.
> 
> qemu-img: Could not open 'alpine-latest/disk.qcow2': Could not open 'alpine-latest/disk.qcow2': No such file or directory
> ```

Hmm.  Very strange. Like back to front.  

Didn't do that for me.  

Thanks for that .

What happens if you do a direct `qemu-img info` on the disk?  Or is it the same on all the disks?

**Comment by flexiondotorg** [comment]
Closed via #986

**Pull request closed without merging**
