### PR TITLE
🏗️ Lint TEST: review :dog: 

### PR DESCRIPTION
**Pull request by zen0bit**
# Please leave this open
For my testing of github `actions/linting` between different organizations.
### What's best for us...
# Not intended to merge
But for actions to work, this needs to be marked `green`

Shellcheck in github action thanks to reviewdog

This GitHub token doesn't have write permission of Review API
It needs to be switched?

Interested @flexiondotorg?

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@zen0bit Can this be closed now?

**Comment by zen0bit** [comment]
wait a bit

**Review by flexiondotorg — COMMENTED** [review]
Why does `quickemu-check` have `permissions:` declared but `quickget-check` does not?

How is is the `reviewdog-PR.yml` different from: https://github.com/quickemu-project/quickemu/blob/master/.github/workflows/reviewdog.yml

I disable the above on PRs because it made code review impossible with all the shellcheck warnings.

**Comment by zen0bit** [comment]
> I disable the above on PRs because it made code review impossible with all the shellcheck warnings.

With disabled reviewdog I cant see outputs
I can't choose the right configurations
Actions work from different repos differently, between organizations/owners and inside one account, so I have to test outside of my territory
La pardon :wink: 

I have different PR to choose program best suited for us.
And secondly I have to test a lot of different parts

Not that easy and I am just trying..

To do the best whats possible

**Pull request closed without merging**
