### PR TITLE
fix for qemu-img error on new installs

### PR DESCRIPTION
**Pull request by TuxVinyards**
make sure a disk exists before trying to check it

fix for disk img error

### CODE REVIEW

**Comment by zen0bit** [comment]
rebase not merge master branch!

**Comment by zen0bit** [comment]
Try lazygit...
https://www.youtube.com/watch?v=_REmkoIyPW0

**Comment by TuxVinyards** [comment]
@zen0bit  I am even more confused after that :rofl: 

I looked in the GitHub docs and they said just to click on  'update'.    That's what I did.   I opened the branch and clicked on the 'Sync' button.  GitHub seemed to be perfectly happy.  Local and remotes seem fine to me.  Not getting any Git complaints.

It looks the same as a rebase to me. Just different words. 

@flexiondotorg   Let me know if you want me to resubmit.   I'll just delete and redo.  Easier all round.  

It's  only a single copy and paste of about twelve characters, if it doesn't work.   

The other commit for MacOS  #1119 is  single block paragraph ...

**Review by flexiondotorg — APPROVED** [review]
Thanks, I'd seen this but not got around to fixing it.

**Pull request merged**
