### PR TITLE
Add Chimera Linux

### PR DESCRIPTION
**Pull request by zen0bit**
[homepage](https://chimera-linux.org/)

### CODE REVIEW

**Comment by zen0bit** [comment]
chimera

**Review by flexiondotorg — APPROVED** [review]

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
PLease update this pull request to use the full name `chimeralinux`

**Comment by zen0bit** [comment]
> PLease update this pull request to use the full name `chimeralinux`

**Review by zen0bit — COMMENTED** [review]
ready

**Review by zen0bit — COMMENTED** [review]
rebased and changed to chimeralinux
Ready to review...

Don't know how to get rid of "Changes requested" in PR
(In more my PRs, all rebased...)

**Comment by zen0bit** [comment]
continues in #892

**Pull request closed without merging**
