### PR TITLE
📦 NEW: add Primtux support

### PR DESCRIPTION
**Pull request by DaffyDuke**
Please add [Primtux](https://primtux.fr) support, a Linux distribution to help children learn fast :)

### CODE REVIEW

**Comment by zen0bit** [comment]
Don't work for me...
fix PR in your repo

**Comment by zen0bit** [comment]
Distro not to friendly for non French person...

**Comment by DaffyDuke** [comment]
You're right, it's only French speaking people. And we are using quickget in English 😬What's your error? Of course I used it before PR or it did note make sense.

**Comment by zen0bit** [comment]
I actually tested on Chimera Linux
Maybe thats reason (wget2)

But no hash check...

**Comment by lj3954** [comment]
Yes, if wget symlinks to wget2 (which it does on Fedora 40, currently Rawhide, and possibly some other distros), you won't be able to check where a URL redirects. I made an issue on this and my PR has a fix.

**Comment by zen0bit** [comment]
Included in #892...

**Comment by flexiondotorg** [comment]
Closed via #986

**Pull request closed without merging**
