### PR TITLE
Added support for netboot

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by zen0bit** [comment]
ipxe support added
mentioned here: #267

**Comment by zen0bit** [comment]
I get rid of empty lines again :) I dont like them...

**Comment by flexiondotorg** [comment]
What a nifty addition. Please can you remove the whitespace additions in this pull request before I merge it :slightly_smiling_face:

**Comment by zen0bit** [comment]
repaired, included in #342

**Pull request closed without merging**
