### PR TITLE
Initial support for fzf

### PR DESCRIPTION
**Pull request by zen0bit**
Quick and dirty but its working for me..
Not all CDs tested...

#339

### CODE REVIEW

**Comment by mark2185** [comment]
And what if the user doesn't have `fzf` installed?

**Comment by zen0bit** [comment]
Could be closed solved in  #346 ...

**Comment by flexiondotorg** [comment]
I agree with @mark2185 on this. Please add guard rails to catch the scenario where `fzf` is not available.

**Comment by the-mentor** [comment]
@zen0bit i think you forgot to include  the releaselist file that you are catting.

Also i don't know if fzf is included in all the distros that quickemu supports

**Comment by zen0bit** [comment]
repaired included in #353

**Pull request closed without merging**
