### PR TITLE
#651 - quickemu indent standardization (4) no code changes

### PR DESCRIPTION
**Pull request by dabrown645**
I noticed someone already did quickget here are similar changes for quickemu (there) are no code changes just indent consistency to 4 spaces. Additionally updated .editorconfig with 4 for indent in quickemu.

### CODE REVIEW

**Comment by TuxVinyards** [comment]
As my comment to #826

I agree it seems strange to have half at 2 and half at 4. But I tend to think most people are moving to 2 space these days.

**Comment by dabrown645** [comment]
I agree with you that 2 is what I prefer. I opened an issue about consistency and was waiting on decision on 2 or 4 then I noticed that someone posted a pull request for quickget (817) with indent of 4 so I submitted quickemu with 4 for consistency. I all agree I am willing change to 2 but in the meantime consistency is the best choice.

**Comment by TuxVinyards** [comment]
I was musing with this whole 2 or 4 thing this morning & was wondering how long it might take to change quickemu or quickget  to 2 or 4 space, either way.  

These VS Code extensions are quite neat and can change the whole script in a matter of seconds:

[https://marketplace.visualstudio.com/items?itemName=Compulim.indent4to2](url)

[https://marketplace.visualstudio.com/items?itemName=ephoton.indent-switcher](url)

The first one only bothers with going from 4 to 2, which probably says something in itself.

I changed  the whole of quickemu from 2 to 4 to see what it looked like and discovered that  function get_port was already at 4 at ended up changed to 6  :rofl:

**Comment by flexiondotorg** [comment]
Let's go with 4 spaces for indentation, take our medicine and get a consistent indentation pull request merged.

Please rebase this pull request :bow:

**Comment by dabrown645** [comment]
I have been looking at resolving conflicts but the changes between 1049 setup keyboard and 1105 setup keyboard layout don't make any since looks like some code around 1254 The OSK parameter ... and doesn't look like it belongs between setup keyboard and setup keyboard layout.

**Comment by Jai-JAP** [comment]
@dabrown645 you can use shfmt to ease your work.

[https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format](This) is useful if you use VSCode

**Comment by dabrown645** [comment]
I looked at resolving conflicts again and 1, 3, 5, and 6 are straight forward and easy to resolve. It is a different issue with 2 and  4. In 2 when I compare with master it looks like it is try to merge into an if statement 27 lines higher the where it is in the current master. Item 6 is the same kind of issue only it looks like over 1000 lines between where code is in master and where it wants to be merged here

If it is easier I can take the current master and redo the refactor and submit a new pull

**Pull request closed without merging**
