### PR TITLE
Older mac fix - improvements

### PR DESCRIPTION
**Pull request by TuxVinyards**
TEST on OLDER RYZEN and notebooks please

Same Lines as already tested as working by @lj3954  but with revised greps  based on further research.

See added links  and notes.  Also see comments to #1116

### CODE REVIEW

**Comment by TuxVinyards** [comment]
Something else to note is that Penryn is only a two core baseline CPU model dating from 2007.  Even Haswell is getting long in the tooth at 2014.  <https://qemu.readthedocs.io/en/v9.0.0/system/qemu-cpu-models.html#preferred-cpu-models-for-intel-x86-hosts>

It might be worth considering Catalina plus to run on Haswell.  Same Ryzen tested formula as used for Ventura but with basic avx, not avx2.

**Comment by lj3954** [comment]
> Penryn is only a two core baseline CPU model dating from 2007

Is there any real performance or usability difference caused by emulating an older CPU?

**Comment by TuxVinyards** [comment]
I would imagine in the same way that a newer physical CPU has extra instruction sets and has more cores ... 

And that Nick Sherlock seems to use the newer models where possible. 

There's somewhere that I read in Qemu docs that Penryn should only be used for legacy emulation too.

**Comment by lj3954** [comment]
> extra instruction sets

Are they being made use of in this case? macOS clearly is able to boot with the penryn argument; missing instructions should make the system fail to boot or crash regularly. More instruction sets is the entire reason why compatibility is reduced when emulating newer CPUs, and therefore only the bare minimum that fully supports the guest OS should be used.

> has more cores

The amount of cores has nothing to do with what CPU you emulate. You can emulate a 486 with 32 cores if you really want to.

**Comment by flexiondotorg** [comment]
Duplicated in #1119

**Pull request closed without merging**
