### PR TITLE
fix blendOS downloads

### PR DESCRIPTION
**Pull request by TuxVinyards**
VM PATH needed a tweak

### CODE REVIEW

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
These changes for blendos should be in a function specific to blendos, not in the general code path.

**Comment by TuxVinyards** [comment]
> These changes for blendos should be in a function specific to blendos, not in the general code path.

I did try that.  The trouble is, that  `$RELEASE` contains a forward slash and `web_get`  needs to have things presented to it in that fashion or it won't download.

 The standard  `$VM_PATH`   assembly uses  `$RELEASE`  as  component,  so we have to change things at that point, after the downloads but before writing to hard drive.  If we don't change it, we end up with a broken distro name and sub folders being created, with the .conf file inside the main VM folder.

Screenshot at 2024-04-13 13-52-11

So, in the same way that both Manjaro & Fedora have to have special entries in that section, we unfortunately have to do that here too .....

**Comment by lj3954** [comment]
I think we can easily use this data to separate it into releases & editions instead. Also, a temp file definitely isn't needed to store this plain text data. I'll have a PR up for these changes in a little bit.

**Comment by TuxVinyards** [comment]
Good work Liam.  I woke up thinking along similar lines this morning.  Good editions filter.

Hopefully no grumbles from @lj3954  on this being a combined effort   :rofl:

**Pull request closed without merging**
