### PR TITLE
Add quickfzf 0.3

### PR DESCRIPTION
**Pull request by zen0bit**
Simple TUI wrapper for quickemu

continuation of #610

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@zen0bit I think this would be better maintained as it's own project.

Would you be interested in me create a "quickfzf" project under the "quickemu-project" GitHub organisation where we can collaborate?

**Comment by zen0bit** [comment]
why not...

**Comment by zen0bit** [comment]
Preparation for #801
Not yet functions implemented!

**Comment by zen0bit** [comment]
I will reopen this later in wiki since, we have it...

**Pull request closed without merging**
