### PR TITLE
Add TUXEDO OS

### LINKED ISSUE #721: Add support for TUXEDO OS
Hi,

Support for TUXEDO OS would be great.
https://www.tuxedocomputers.com/en/TUXEDO-OS_1.tuxedo
https://os.tuxedocomputers.com/

### PR DESCRIPTION
**Pull request by zen0bit**
Closes #721

### CODE REVIEW

**Comment by zen0bit** [comment]
running vm not yet tested

**Review by philclifford — APPROVED** [review]

**Comment by philclifford** [comment]
Please link to Issue by adding keyword reference to the description comment:
Closes #721

**Comment by zen0bit** [comment]
tuxedoos

**Comment by flexiondotorg** [comment]
I am not going to accept distros that are primarily designed for/by OEMs as they will often carry hardware-specific enablement that is unnecessary in VMs.

**Pull request closed without merging**
