### PR TITLE
add arcolinuxl iso to the list

### PR DESCRIPTION
**Pull request by erikdubois**
Hope I have added everything the right way.

I was able to download the iso on my end.

### CODE REVIEW

**Comment by philclifford** [comment]
Hi Erik,
Thanks for the contribution. Your PR looks fine to me.  It would be even more helpful if you could also add Arco Linux to the README.md (It's loosely grouped at the top so next to Arch would seem sensible ;-)  and the list near the bottom is alphabetical ).  
Do you have a nice svg logo to hand for incorporation by our [artistic wizards](https://github.com/quickemu-project/quickemu-icons/issues/12) ?

Nice project btw!

**Comment by erikdubois** [comment]
Added the readme

**Comment by erikdubois** [comment]
Here is a link that will probably be stable over the coming years.

https://github.com/arcolinux/arcolinux-system-config/blob/master/usr/share/icons/hicolor/scalable/places/start-here-arcolinux.svg

**Review by philclifford — COMMENTED** [review]
Thanks Erik. There's also a list of `parameters` around line 180...

**Comment by erikdubois** [comment]
What file are you referring to? Line 180?

**Comment by erikdubois** [comment]
ok the readme file

**Comment by erikdubois** [comment]
done

**Comment by philclifford** [comment]
Thanks. Much appreciated.

**Comment by daPhipz** [comment]
Thanks @erikdubois for the icon links! I'll have a look in the coming days.

**Pull request merged**
