### PR TITLE
Initial gentoo support

### PR DESCRIPTION
**Pull request by guyosi**
This is initial support for Gentoo Linux to quickget,it does download and boot.

### CODE REVIEW

**Comment by daPhipz** [comment]
When running `quickget gentoo latest`, I get

```
dirname: fehlender Operand
„dirname --help“ liefert weitere Informationen.
ERROR! Failed to download /20211128T170532Z/install-amd64-minimal-20211128T170532Z.iso. Try running 'quickget' again.
```

which roughly translates to

```
dirname: missing operand
„dirname --help“ for further information.
ERROR! Failed to download /20211128T170532Z/install-amd64-minimal-20211128T170532Z.iso. Try running 'quickget' again.
```

https://bouncer.gentoo.org/fetch/root/all/releases/amd64/autobuilds/${RELEASE}-iso.txt looks like this as of 2021-12-01 11:10 German time:

```
# Latest as of Wed, 01 Dec 2021 07:00:01 +0000
# ts=1638342001
20211128T170532Z/admincd-amd64-20211128T170532Z.iso 648019968
20211128T170532Z/install-amd64-minimal-20211128T170532Z.iso 457179136
```

My first guess is that `grep` fails, since there is no string `"Location"` anywhere in the file above.
Will investigate further!

**Comment by philclifford** [comment]
> My first guess is that `grep` fails, since there is no string `"Location"` anywhere in the file above. Will investigate further!
It should find "Location" in the file it's `wget`ing.  Maybe you hit it during a build ??
It's worked reliably for me and the following still does
``` 
eval $( wget  -O/tmp/gentoolatest https://bouncer.gentoo.org/fetch/root/all/releases/amd64/autobuilds/${RELEASE}-iso.txt 2`>&1 |grep Location | awk '{print "LOCAT="$2}' )
    LOCAT=$(dirname ${LOCAT})
    eval $( awk '/admincd-amd64/ {print "ADMIN="$1}; /install-amd64-minimal/ {print "INSTALLMIN="$1}' /tmp/gentoolatest )
    URL="${LOCAT}/${INSTALLMIN}"
    ISO=$(basename "${INSTALLMIN}" )

```

Might need to quote the grep expression and also add something to catch absence (or oddness) in the `${RELEASE}-iso.txt `
And maybe quietly remove /tmp/gentoolatest at the end.

**Comment by philclifford** [comment]
[Heads-up](https://github.com/quickemu-project/quickemu-icons/issues/12) icon wizards

**Comment by philclifford** [comment]
@guyosi you'll need to do a little merging and conflict resolution to get this PR to be mergeable again (this is normal - we all step on each others toes at merge time ). Maybe worth setting this to draft until it is re-tested and confirmed working again once it has no conflicts.

@flexiondotorg note I may have added a bug to this that "works for me" but not @daPhipz  - see the [comment](https://github.com/quickemu-project/quickemu/pull/255#issuecomment-984193274) a couple above.

**Comment by guyosi** [comment]
Finished squashing the bugs, there shouldn't be any conflicts.

**Pull request merged**
