### PR TITLE
quickget: show info about operating system WIP

### PR DESCRIPTION
**Pull request by zen0bit**
Since is a lot of supported operating system.
It could be useful show short info about them..

- [x] os_about function
- [x] all supported OS - tried to include only first sentence from homepage, but sometimes I maked my own from about pages etc.
Feel free to EDIT.
- [ ] guickget argument
- [ ] show info somewhere

### CODE REVIEW

**Comment by TuxVinyards** [comment]
More good work on adding OS info :+1: 

Couple of things that I noticed, that you might want to tweak:

Ubuntu-Kylin text needs to be in English ?

Linux Mint  should probably lead with the phrase: Ubuntu based. 

And Manjaro  should probably lead with:  Arch based.  

Lubuntu should probably say that it is lightweight.  Also that it  features the LXDE/LXQT  desktop.

Same with Ubuntu Mate.  Needs to say Mate desktop somewhere.

Void and Ubuntu-Mate  also need initial Caps

:rocket:

**Comment by TuxVinyards** [comment]
PS noticing the info line on Kali-linux  ...   Should we have Parrot OS on quickget?   It's probably number 2 in the pentest OS's.  Balanced approach ...

**Comment by zen0bit** [comment]
> More good work on adding OS info 👍
> 
> Couple of things that I noticed, that you might want to tweak:
> 
> Ubuntu-Kylin text needs to be in English ? - ? I changed Ubuntu-Kylin and Deepin to eng version since quickemu is only in english (yet - thinking about translations for a while 🤔)
> - ? 
> Linux Mint should probably lead with the phrase: Ubuntu based.
>  - 👍
> And Manjaro should probably lead with: Arch based.
>  - 👍
> Lubuntu should probably say that it is lightweight. Also that it features the LXDE/LXQT desktop.
>  - 👍
> Same with Ubuntu Mate. Needs to say Mate desktop somewhere.
>  - 👍
> Void and Ubuntu-Mate also need initial Caps
>  - 👍

ParrotOS 🤔

**Comment by TuxVinyards** [comment]
Translations would be good but can get very complex.  Like .po files.

Technically you could have a relational array in an auxiliary text file but this again gets very restrictive as things start to become immutable. Something for mature projects only, I think

**Comment by zen0bit** [comment]
> PS noticing the info line on Kali-linux ... Should we have Parrot OS on quickget? It's probably number 2 in the pentest OS's. Balanced approach ...

#893

**Comment by zen0bit** [comment]
Included in #892

**Comment by philclifford** [comment]
This feature is unnecessary and adds a maintenance burden and an additional barrier to contributors.

**Comment by TuxVinyards** [comment]
@philclifford  It's only a one off, one liner?

I think this would be quite good for people browsing the download lists as they wouldn't have to keep opening the OS home pages just to get a basic synopsis.

I will be adding this to qqX irrespectively.

Link maintenance is a lot more work.   😂

All the best 2024 🥂

**Pull request closed without merging**
