### PR TITLE
sort functions

### PR DESCRIPTION
**Pull request by zen0bit**
Functions sorted alphabetically
Removed and added some empty lines..

No code change!

### CODE REVIEW

**Comment by philclifford** [comment]
Just to note - there might be about to be a couple of dozen new functions appearing so it is likely this will get conflicted and so not merged ... Thanks either way!

**Comment by zen0bit** [comment]
I will check again after https://github.com/quickemu-project/quickemu/pull/324 will be merged...

**Comment by zen0bit** [comment]
Could be closed solved in  #346 ...

**Comment by flexiondotorg** [comment]
Thanks for working on this but, but I am reluctant to merge this as it breaks the ability to easily merge pull requests based on the main branch.

**Pull request closed without merging**
