### PR TITLE
feat: finalization of new UI = help message

### PR DESCRIPTION
**Pull request by zen0bit**
Used arguments etc. Not setted in stone!

I want
# disscussion
and approval or correction (also grammar)

PS: Not everything is implemented yet
(myiso .. )

```
help_message() {
    #shellcheck disable=SC2016
    printf '                           _              _
         __ _ _   _ _  ___║ ║ ____ _  ___║ ║_
        / _` ║ ║ ║ ║ ║/ __║ ║/ / _` ║/ _ \ __║
       ( (_║ ║ ║_║ ║ ║ (__║   < (_║ ║  __/ ║_      MIT
        \__, ║\__,_║_║\___║_║\ \__, ║\___║\__║   license
           ║_║  version: %s ║___/ part of QUICKEMU project
 QEMU %s --------------------------------------------------
         > Quickly create and run optimised Linux, <
       > Windows and macOS desktop virtual machines. <
   homepage   -    Not Yet
  repository  - https://github.com/quickemu-project/quickemu
 official GUI - https://github.com/quickemu-project/quickgui
  by Wimpy https://github.com/flexiondotorg and contributors
 Discord - https://discord.gg/wimpy-s-world-712850672223125565
--------------------------------------------------------------

Basic Usage:
 quickget <os> <release> [edition]
 quickget alpine latest

Advanced Usage:
 quickget <arg> [path] <os> [re] [ed]
 quickget -d peppermint latest devuan-xfce

Posible arguments:
 --os-info         (-oi) <os>           : Show info about OS
 --show-crede      (-sc) <os>           : Show OS default credentials
 --open-homepage   (-oh) <os>           : Open OS homepage in default browser
 --download-iso    (-di) <os> <re> [ed] : Just download ISO
 --my-iso          (-mi) <os> <ISO path>: Create VM with downloaded ISO*
 --version          (-v)                : Show version and exit
 --help             (-h)                : Show this help message and exit
   * To prepare custom VM config (Not supported by quickget) use:
     quickget --custom <some name> <path to ISO>
-------------- for developers / testing ----------------------
 --show-homepage   (-sh) <os>           : Show OS homepage URL
 --show-iso        (-si) <os> <re> [ed] : Show·ISO·download·URL
 --test-iso        (-ti) <os> <re> [ed] : Test if ISO is available
 --show-isos       (-ss) <os>           : Show all ISOs of OS
 --test-isos       (-ts) <os>           : Test all ISOs of OS
 --list-csv        (-lc)                : Show lists in csv format
 --list-json       (-lj)                : Show lists in json format
 --list-supported  (-ls)                : List all OS, releases and editions
 --list-isos       (-li)                : List all supported ISOs
 --list-test       (-lt)                : Test if all ISOs are available
--------------------------------------------------------------
supported Operating Systems:\n' "$(quickemu --version)" "$(qemu-x86_64 -version | head -1 | cut -d' ' -f3)"
    os_support | fold -s -w "$(tput cols)"
    exit 0
}
```

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Here are my thoughts based on the `help_message()` function as it exists now:

```shell
help_message() {
    #shellcheck disable=SC2016
    printf '                           _              _
         __ _ _   _ _  ___║ ║ ____ _  ___║ ║_
        / _` ║ ║ ║ ║ ║/ __║ ║/ / _` ║/ _ \ __║
       ( (_║ ║ ║_║ ║ ║ (__║   < (_║ ║  __/ ║_      MIT
        \__, ║\__,_║_║\___║_║\ \__, ║\___║\__║   license
           ║_║  version: %s ║___/ part of QUICKEMU project
 QEMU %s --------------------------------------------------
         > Quickly create and run optimised Linux, <
       > Windows and macOS desktop virtual machines. <
   homepage   -    Not Yet
  repository  - https://github.com/quickemu-project/quickemu
 official GUI - https://github.com/quickemu-project/quickgui
  by Wimpy https://github.com/flexiondotorg and contributors
 Discord - https://discord.gg/wimpy-s-world-712850672223125565
--------------------------------------------------------------

Basic Usage:
 quickget <os> <release> [edition]
 quickget alpine latest

Advanced Usage:
 quickget <arg> [path] <os> [re] [ed]
 quickget -d peppermint latest devuan-xfce

Posible arguments:
 --os-info         (-oi) <os>           : Show info about OS
 --show-crede      (-sc) <os>           : Show OS default credentials
 --open-homepage   (-oh) <os>           : Open OS homepage in default browser
 --download-iso    (-di) <os> <re> [ed] : Just download ISO
 --my-iso          (-mi) <os> <ISO path>: Create VM with downloaded ISO*
 --version          (-v)                : Show version and exit
 --help             (-h)                : Show this help message and exit
   * To prepare custom VM config (Not supported by quickget) use:
     quickget --custom <some name> <path to ISO>
-------------- for developers / testing ----------------------
 --show-homepage   (-sh) <os>           : Show OS homepage URL
 --show-iso        (-si) <os> <re> [ed] : Show·ISO·download·URL
 --test-iso        (-ti) <os> <re> [ed] : Test if ISO is available
 --show-isos       (-ss) <os>           : Show all ISOs of OS
 --test-isos       (-ts) <os>           : Test all ISOs of OS
 --list-csv        (-lc)                : Show lists in csv format
 --list-json       (-lj)                : Show lists in json format
 --list-supported  (-ls)                : List all OS, releases and editions
 --list-isos       (-li)                : List all supported ISOs
 --list-test       (-lt)                : Test if all ISOs are available
--------------------------------------------------------------
supported Operating Systems:\n' "$(quickemu --version)" "$(qemu-x86_64 -version | head -1 | cut -d' ' -f3)"
    os_support | fold -s -w "$(tput cols)"
    exit 0
}
```

## General feedback

Less is more :slightly_smiling_face: 

- Remove "homepage   -    Not Yet" from the header.
- Remove "official GUI - https://github.com/quickemu-project/quickgui" from the header.
- Remove "by Wimpy https://github.com/flexiondotorg and contributors" from the header.
- Change "Discord - https://discord.gg/wimpy-s-world-712850672223125565" to "Discord: https://wimpysworld.io/discord"
- Remove `qemu-x86_64 -version` from the header.
  - It is the only use of QEMU (the hypervisor) in `quickget` and isn't needed for anything so reporting the QEMU version is redundant in `quickget`.
  - It is another place we'll need to adapt as we add support for running foreign architecture VMs.
- `quickqui` uses `list`, `list_csv` and `list_json`
  - **Those arguments need to be preserved for backwards compatibility.**
- In the *Advanced Usage:* use the long hand arguments, such as `--download-only` instead of `-d`, so the examples are more informative/useful.
- Drop `--my-iso` and any custom configuration creation.
  - Creating a VM requires more inputs than just the ISO to create a working configuration, such as the guest, boot type, and boot. And this is the central purpose of `quickget`. 
  - Users requiring a bespoke configuration can hand craft them.
  - I want to keep `quickget` as a tool that automatically does the right thing. I don't want to recreate the complexity of VirtualBox, etc.

## Arguments

- Change `--os-info` to just `--info`
- Change `--download-iso` to `--download`
- Change `--test-iso` to `--check`
- Change `--test-isos` to `--check-all`
- Change `--show-iso` to `--url`
- Change `--show-isos` to `--url-all`
- Change `--list-isos` to `--list-urls`
- Change `--list-test` to `--test-urls`
- Change `--list-supported` to `--list`
- Drop `--show-crede`.
  - If showing the default login credentials is something we want to do, it should be part of `--info`
- Drop `--show-homepage`
  - It should just be part of `--info`
  
## Proposal (**not tested for syntax**)

Here is my mock-up based on the above feedback, which hopefully makes things more clear, and includes revised long-hand and shot-hand arguments.

```shell
help_message() {
    #shellcheck disable=SC2016
    printf '                           _              _
         __ _ _   _ _  ___║ ║ ____ _  ___║ ║_
        / _` ║ ║ ║ ║ ║/ __║ ║/ / _` ║/ _ \ __║
       ( (_║ ║ ║_║ ║ ║ (__║   < (_║ ║  __/ ║_      MIT
        \__, ║\__,_║_║\___║_║\ \__, ║\___║\__║   license
           ║_║  version: %s ║___/ part of Quickemu project
 QEMU %s --------------------------------------------------
         > Quickly create and run optimised Linux, <
       > Windows and macOS desktop virtual machines. <

 Project - https://github.com/quickemu-project/quickemu
 Discord - https://wimpysworld.io/discord
--------------------------------------------------------------

Basic Usage:
 quickget <os> <release> [edition]
 quickget ubuntu 22.04

Advanced Usage:
 quickget <arg> [path] <os> [re] [ed]
 quickget --download ubuntu 22.04

Arguments:
 --info             (-i) <os>           : Show info about OS
 --download         (-d) <os> <re> [ed] : Download the ISO only; no VM configuration
 --open-homepage    (-o) <os>           : Open homepage for the OS
 --version          (-v)                : Show version
 --help             (-h)                : Show this help message
------------------- For testing & development ----------------
 --check            (-c)  <os> [re] [ed] : Check download an OS release/edition is available
 --check-all        (-ca) <os>           : Check all downloads for an OS are available
 --url              (-u)  <os> <re> [ed] : Show download URL for an OS release/edition
 --url-all          (-ua) <os>           : Show all download URLs for an OS
 --list             (-l)                 : List all supported systems in plain text
 --list-csv         (-lc)                : List all supported systems in csv format
 --list-json        (-lj)                : List all supported systems in json format
 --list-urls        (-lu)                : List all supported systems download URLs
 --test-urls        (-tu)                : Check all downloads for all OSs are available
--------------------------------------------------------------
Supported Operating Systems:\n' "$(quickemu --version)"
    os_support | fold -s -w "$(tput cols)"
    exit 0
}
```

## Code folding

It should be possible to fold some code, as it looks like:

- `--check` and `--check-all` are orthogonal and that only `--check` is required that could accept `<re>` and `[ed]` as optional arguments.
- `--url` and `--url-all` are orthogonal and that just `--url` is required that could accept `<re>` and `[ed]` as optional arguments.

**Comment by zen0bit** [comment]
> Less is more 🙂

:+1:  
>     * Remove "homepage   -    Not Yet" from the header.
> 
>     * Remove "official GUI - [quickemu-project/quickgui](https://github.com/quickemu-project/quickgui)" from the header.
> 
>     * Remove "by Wimpy [@flexiondotorg](https://github.com/flexiondotorg) and contributors" from the header.
> 
>     * Change "Discord - [discord.gg/wimpy-s-world-712850672223125565](https://discord.gg/wimpy-s-world-712850672223125565)" to "Discord: [wimpysworld.io/discord](https://wimpysworld.io/discord)"
> 
>     * Remove `qemu-x86_64 -version` from the header.
>       
>       * It is the only use of QEMU (the hypervisor) in `quickget` and isn't needed for anything so reporting the QEMU version is redundant in `quickget`.
>       * It is another place we'll need to adapt as we add support for running foreign architecture VMs.

:+1: 
>     * `quickqui` uses `list`, `list_csv` and `list_json`
>
>       * **Those arguments need to be preserved for backwards compatibility.**

Is that really needed? For what/who may I ask? (quickgui?)
I think if we have arguments only with dashes could make things easier for us
same as help. I leaved that four or five arguments for help...

>     * In the _Advanced Usage:_ use the long hand arguments, such as `--download-only` instead of `-d`, so the examples are more informative/useful.

:+1: 
>     * Drop `--my-iso` and any custom configuration creation.

>       * Creating a VM requires more inputs than just the ISO to create a working configuration, such as the guest, boot type, and disk space. Doing this well is the central purpose of `quickget`.
>       * Users requiring a bespoke configuration can handcraft them.
>       * I want to keep `quickget` as a tool that automatically does the right thing. I don't want to recreate the complexity of VirtualBox, etc.

This is needed for me. I just want try run any ISO (~/ or https://) with default linux configuration.
 Will work for most. I actually in 99% cases needs to change only efi/legacy configuration (don't care about disc now [Live ISO])
Thats all. Named could be whatever.

Also if we remove one of tests/shows I am inclined to remove testing all not testing all of OS
Since testing all supported ISOs, if I have os support list is easy
Parsing releases and editions to test one by one not so easy

So I will remove testing and showing all ISOs and add instead testing all from one distro. We could speak about distros since with win don't work anyway.
Not checked latest changes..
 
> ## Code folding
> 
> It should be possible to fold some code, as it looks like:
> 
>     * `--check` and `--check-all` are orthogonal and that only `--check` is required that could accept `<re>` and `[ed]` as optional arguments.
> 
>     * `--url` and `--url-all` are orthogonal and that just `--url` is required that could accept `<re>` and `[ed]` as optional arguments.

 aha

 I will use short one anyway. But long are nice also, if one isn't familiar with program... 

 OK

PS: out of topic: Merged HoloISO changes don't work for me...

**Comment by zen0bit** [comment]
> This is needed for me. I just want try run any ISO (~/ or https://) with default linux configuration.
> Will work for most. I actually in 99% cases needs to change only efi/legacy configuration (don't care about disc now [Live ISO])
> Thats all. Named could be whatever.
> usage: `quickget --my-iso <super name> ~/git/newone` or `quickget --my-iso <even better name> https://nowhere.com/bestisointheworld.iso`
> We don't need to do nothing fancy and add super usefull feature

Maybe with optional -l legacy flag for legacy BIOS

**Comment by zen0bit** [comment]
Less is more 🙂

👍
> * Drop `--show-crede`.
>   
>   * If showing the default login credentials is something we want to do, it should be part of `--info`
> 
> * Drop `--show-homepage`
>   
>   * It should just be part of `--info`

I think better will be ADD something instead

I want all part of info printable separately `-[ABCH]` for About Basedof Credentials Homepage

# Less is more :rofl:

**Comment by zen0bit** [comment]
> Less is more 🙂
> 
> 👍
> 
> > * Drop `--show-crede`.
> >   
> >   * If showing the default login credentials is something we want to do, it should be part of `--info`
> > * Drop `--show-homepage`
> >   
> >   * It should just be part of `--info`
> 
> Already is **but**...
> 
> I think better will be ADD something instead
> 

# getops LABCH

**Comment by zen0bit** [comment]
```
help_message() {
    #shellcheck disable=SC2016
    printf '                           _              _
         __ _ _   _ _  ___║ ║ ____ _  ___║ ║_
        / _` ║ ║ ║ ║ ║/ __║ ║/ / _` ║/ _ \ __║
       ( (_║ ║ ║_║ ║ ║ (__║   < (_║ ║  __/ ║_      MIT
        \__, ║\__,_║_║\___║_║\ \__, ║\___║\__║   license
           ║_║  version: %s ║___/ part of Quickemu project
 QEMU %s --------------------------------------------------
         > Quickly create and run optimised Linux, <
       > Windows and macOS desktop virtual machines. <

 Project - https://github.com/quickemu-project/quickemu
 Discord - https://wimpysworld.io/discord
--------------------------------------------------------------

Basic Usage:
 quickget <os> <release> [edition]
 quickget ubuntu 22.04

Advanced Usage:
 quickget <arg> [path] <os> [re] [ed]
 quickget --download ubuntu 22.04

Arguments:
 <12345>                 <os>           : Show info about OS*
 --download         (-d) <os> <re> [ed] : Download the ISO only; no VM configuration
 --iso-somwhere     (-i) <os> <ISO path>: Create VM with downloaded ISO*
 --open-homepage    (-o) <os>           : Open homepage for the OS
 --version          (-v)                : Show version
 --help             (-h)                : Show this help message
------------------- For testing & development ----------------
 --check            (-c)  <os> [re] [ed] : Check download an OS release/edition is available
 --check-all        (-ca) <os>           : Check all downloads for an OS are available
 --url              (-u)  <os> <re> [ed] : Show download URL for an OS release/edition
 --url-all          (-ua) <os>           : Show all download URLs for an OS
 --list             (-l)                 : List all supported systems in plain text
 --list-csv         (-lc)                : List all supported systems in csv format
 --list-json        (-lj)                : List all supported systems in json format
 --list-urls        (-lu)                : List all supported systems download URLs
 --test-urls        (-tu)                : Check all downloads for all OSs are available
--------------------------------------------------------------
Supported Operating Systems:\n' "$(quickemu --version)"
    os_support | fold -s -w "$(tput cols)"
    exit 0
}
```

**Comment by zen0bit** [comment]
I take silence as approval :smiley:

Implemented getopts. And all (less) arguments except iso-somewhere

But I need write use of info into help message
how to?

Currently:

 - 1 = Logo + pretty name (Or better separate logo from Pretty name?)
 - 2 = Based of
 - 3 = Credentials
 - 4 = Homepage
 - 5 = Short info

Use as first argument with choosed OS after that

quickget -12345 ubuntu = shows everything
quickget -4 ubuntu = shows homepage
quickget -51 ubuntu = shows info and then logo

**Comment by zen0bit** [comment]
What about this?
```
help_message() {
    #shellcheck disable=SC2016
    printf '                           _              _
         __ _ _   _ _  ___║ ║ ____ _  ___║ ║_
        / _` ║ ║ ║ ║ ║/ __║ ║/ / _` ║/ _ \ __║
       ( (_║ ║ ║_║ ║ ║ (__║   < (_║ ║  __/ ║_      MIT
        \__, ║\__,_║_║\___║_║\ \__, ║\___║\__║   license
           ║_║  version: %s ║___/ part of Quickemu project
--------------------------------------------------------------
         > Quickly create and run optimised Linux, <
       > Windows and macOS desktop virtual machines. <

 Project - https://github.com/quickemu-project/quickemu
 Discord - https://wimpysworld.io/discord
--------------------------------------------------------------

Basic Usage:
 quickget <os> <release> [edition]
 quickget ubuntu 22.04

Advanced Usage:
 quickget <arg> [path] <os> [re] [ed]
 quickget --download ubuntu 22.04

Arguments:
 -[12345]              <os>           : Show info* about OS
 --download       (-d) <os> <re> [ed] : Download the ISO only; no VM configuration
 --iso-somwhere   (-i) <os> <ISO>     : Download ISo if is URL, then create default linux config for new VM with provided name
 --open-homepage  (-o) <os>           : Open homepage for the OS
 --version        (-v)                : Show version
 --help           (-h)                : Show this help message
-------------- For testing & development ---------------------
 --check          (-c) <os> [re] [ed] : Check download an OS release/edition is available
 --check-all     (-ca) <os>           : Check all downloads for an OS are available
 --url            (-u) <os> <re> [ed] : Show download URL for an OS release/edition
 --url-all       (-ua) <os>           : Show all download URLs for an OS
 --list           (-l)                : List all supported systems in plain text
 --list-csv      (-lc)                : List all supported systems in csv format
 --list-json     (-lj)                : List all supported systems in json format
 --list-urls     (-lu)                : List all supported systems download URLs
 --test-urls     (-tu)                : Check all downloads for all OSs are available
--------------------------------------------------------------
   *info: 1=Logo 2=Based of 3=Credentials 4=Homepage 5=Short info
    Can be used in any combination like -13254 or -52

Supported Operating Systems:\n' "$(quickemu --version)"
    os_support | fold -s -w "$(tput cols)"
}
```

**Comment by zen0bit** [comment]
Also thinking about nicer logo.

Used one is just first, I suggest :wink:

leaving that choice for later...
 ...so?

Any graphic designer here?
I just bit played with figglet and toilet..

**Comment by TuxVinyards** [comment]
> > Is that really needed? For what/who may I ask? (quickgui?)
> > I think if we have arguments only with dashes could make things easier for us
> 
> Yes, `list`, `list_csv` and `list_json` are required for quickgui. They are essentially the "API" to quickemu, but they do not need to be exposed as usbale arguments via `--help`.
> 
>     * If those are removed, then quickgui needs to be updated accordingly.
> 

Ditto for me, kind of.    Removal of  `quickget -t` breaks qqX.   I am working on fixes and updates.  But in the same way as for Quickgui, keeping `-t`  as an undocumented synonym for `--check`  _might_  help mitigate any transitional  problems.   

Currently, qqX runs `-t`  and checks if grep returns the word 'broken' from the output.  

On the other hand,  it could mask problems too.  The better option might be to remove it, in case we forget why it was there and it get removed later causing unexpected breaks.  Providing we get sufficiently long enough a beta/RC time slot I should be able to cope.  

I generally prefer the new API.  I like the idea of being able to directly extract the target URL

At the moment things are so in the air, it's just too difficult code anything against things.   

ALSO  on a slightly related point, I still don't like the Windows LANGS not being hyphenated.  If new users don't quote the bracketed suffix they are going to get the wrong release and keep filing 'it doesn't work' type issues ....

**Comment by flexiondotorg** [comment]
> > Let's not target font logos for this new release, we can put it on the roadmap for a future release.
> 
> That's the plan (Or I pushed icons also here?)

Please keep all distro logo/icon work in a separate branch and PR as it requires some more preparatory work with regards to distro packaging to land the feature.

**Comment by flexiondotorg** [comment]
@zen0bit As #999 is merged, can this be closed?

**Pull request closed without merging**
