### PR TITLE
New🥳year merge

### PR DESCRIPTION
**Pull request by zen0bit**
A lot...
### New feature:
- [x] #864
- [x] #884
- [ ] [partial] Download ISO to (Need check macos etc.)
- [x] Inbuilt MacOS downloading by @lj3954 
- [x] Show info about OS `quickget -i alpine`
Output will look like this:
```
alpine
Pretty name: Alpine Linux
Based of: Independent
Credentials: Unknown
Homepage: https://alpinelinux.org/
Info: Security-oriented, lightweight Linux
distribution based on musl libc and busybox.
```
- [x] Show proper help message
```
                             _              _
           __ _ _   _ _  ___║ ║ ____ _  ___║ ║_
          / _` ║ ║ ║ ║ ║/ __║ ║/ / _` ║/ _ \ __║
         ( (_║ ║ ║_║ ║ ║ (__║   < (_║ ║  __/ ║_      MIT
          \__, ║\__,_║_║\___║_║\ \__, ║\___║\__║   license
             ║_║  version: 4.9.1 ║___/
 QEMU 8.1.3 --------------------------------------------------
       > Quickly create and run optimised Windows, <
       > macOS and Linux desktop virtual machines. <
   homepage   -    Not Yet
  repository  - https://github.com/quickemu-project/quickemu
 official GUI - https://github.com/quickemu-project/quickgui
  by Wimpy https://github.com/flexiondotorg and contributors
 Discord - https://discord.gg/wimpy-s-world-712850672223125565
--------------------------------------------------------------

Basic Usage:
 quickget <os> <release> [edition]
 quickget alpine latest

Advanced Usage:
 quickget <arg> [path] <os> [re] [ed]
 quickget -dt $HOME/Downloads peppermint latest devuan-xfce

Posible arguments:
 --version          (-v)                : Show version and exit
 --help             (-h)                : Show this help message and exit
 --list-json       (-lj)                : Show OS info in json format
 --list-csv        (-lc)                : Show OS info in csv format
 --os-info          (-i) <os>           : Show info about OS
 --os-homepage      (-o) <os>           : Open OS homepage in default browser
 --iso-url-show     (-u) <os> <re> [ed]      : Show ISO download URL
 --iso-url-test     (-t) <os> <re> [ed]      : Test if ISO is available
 --iso-download     (-d) <os> <re> [ed]      : Download ISO (without create VM)
 --iso-download-to (-dt) <pa> <os> <re> [ed] : Download ISO to specified dir

supported Operating Systems:
alma alpine android antix archlinux archcraft arcolinux artix athenaos batocera
bazzite blendos bodhi bunsenlabs cachyos centos-stream chimeralinux crunchbang++
debian deepin devuan dragonflybsd easyos edubuntu elementary endeavouros endless
fedora freebsd freedos garuda gentoo ghostbsd haiku holoiso kali kdeneon
kolibrios kubuntu linuxlite linuxmint lmde mageia manjaro mxlinux netboot netbsd
nixos lubuntu macos openbsd openindiana opensuse oraclelinux peppermint
parrotsec popos porteus primtux reactos rebornos rockylinux siduction slackware
slax slint slitaz solus sparkylinux spiral tails tinycore trisquel truenas-core
truenas-scale ubuntu ubuntu-budgie ubuntucinnamon ubuntukylin ubuntu-mate
ubuntu-server ubuntustudio ubuntu-unity vanillaos void vxlinux windows
windows-server xerolinux xubuntu zorin
```
- [x] OS support list not break in words on end of line `fold -s -w $(tput cols)`
- [x] OS info added to csv
- [x] ERROR functions (make script bit readable)
- [x] small function `cut_1` instead of `cut -d' ' -f1` in HASH and some others

### Added again:
- [x] Windows language by @lj3954

### New distro:
- [x] 📦 Windows Server by @lj3954
```
windows-server
Pretty name: Windows Server
Based of: proprietary
Credentials: Unknown
Homepage: https://www.microsoft.com/en-us/windows-server/
Info: Platform for building an infrastructure of connected applications, networks, and web services.
```
- [x] [📦 Crunchbang++](https://github.com/quickemu-project/quickemu/commit/cafccb1df4b8c1141d027d05132b2fb5f3cdc034)
```
crunchbang++
Pretty name: #!++
Based of: Debian
Credentials: Unknown
Homepage: https://www.crunchbangplusplus.org/
Info: The classic minimal crunchbang feel, now with debian 12 bookworm.
```
- [x] [📦 Slax](https://github.com/quickemu-project/quickemu/commit/bb52aa44acf414a405d6247c09d9e89d9527e072)
```
slax
Pretty name: Slax
Based of: Debian Slackware
Credentials: Unknown
Homepage: https://www.slax.org/
Info: Compact, fast, and modern Linux operating system that combines sleek design with modular approach. With the ability to run directly from a USB flash drive without the need for installation, Slax is truly portable and fits easily in your pocket.
```
- [x] [📦 bazzite](https://github.com/quickemu-project/quickemu/commit/40590ca1bb25f40fbea3a9940bd090b3334b2d3d)
```
bazzite
Pretty name: bazzite
Based of: Fedora,SteamOS
Credentials: Unknown
Homepage: https://github.com/ublue-os/bazzite/
Info: Container native gaming and a ready-to-game SteamOS like.
```
- [x] [📦 Artix Linux](https://github.com/quickemu-project/quickemu/commit/b8b51c82133ca65ef270c715b7aa7384dc6254c2)
```
artix
Pretty name: Artix Linux
Based of: Arch
Credentials: Unknown
Homepage: https://artixlinux.org/
Info: The Art of Linux. Simple. Fast. Systemd-free.
```
- [x] [📦 Athena OS](https://github.com/quickemu-project/quickemu/commit/348b7f9101d21b55d7149b26d7049dc363bd81d4)
```
athenaos
Pretty name: Athena OS
Based of: Arch
Credentials: Unknown
Homepage: https://athenaos.org/
Info: Offer a different experience than the most used pentesting distributions by providing only tools that fit with the user needs and improving the access to hacking resources and learning materials.
```
- [x] [📦 Chimera Linux](https://github.com/quickemu-project/quickemu/commit/7b661f5ac43de6b457c0474113cbd04b10984e6e)
```
chimeralinux
Pretty name: Chimera Linux
Based of: Independent
Credentials: anon:chimera root:chimera
Homepage: https://chimera-linux.org/
Info: Modern, general-purpose non-GNU Linux distribution.
```
- [x] [📦 Slitaz GNU/Linux](https://github.com/quickemu-project/quickemu/commit/810237b0f22be881330a6baf9bd6b9e322b165ab)
```
slitaz
Pretty name: SliTaz
Based of: Independent
Credentials: Unknown
Homepage: https://www.slitaz.org/en/
Info: Simple, fast and low resource Linux OS for servers & desktops.
```
- [x] [📦 SparkyLinux](https://github.com/quickemu-project/quickemu/commit/5c8832e7b5c0fc695b224f73a7a35eecd8b12b1f)
```
sparkylinux
Pretty name: SparkyLinux
Based of: Debian
Credentials: Unknown
Homepage: https://sparkylinux.org/
Info: Fast, lightweight and fully customizable operating system which offers several versions for different use cases.
```
- [x] [📦 Primtux](https://github.com/quickemu-project/quickemu/commit/07a31ee7541c6db7e1264f930b36f05d6672d848) by @DaffyDuke
```
primtux
Pretty name: PrimTux
Based of: Ubuntu
Credentials: Unknown
Homepage: https://primtux.fr/
Info: Upgrade for obsolete equipment and benefiting the school or educational environment in the spirit of education.
```
- [x] [📦 Slint](https://github.com/quickemu-project/quickemu/commit/d6d88238febef34671f9ce0d7f2d63d6966ff416)
```
slint
Pretty name: Slint
Based of: Slackware
Credentials: Unknown
Homepage: https://slint.fr/
Info: Slint is an easy-to-use, versatile, blind-friendly Linux distribution for 64-bit computers. Slint is based on Slackware and borrows tools from Salix. Maintainer: Didier Spaier.
```
- [x] [📦 Parrot Security](https://github.com/quickemu-project/quickemu/commit/b535eeec4f125902c9fffba5f6d9371e7e3a4d5d)
```
parrotsec
Pretty name: Parrot Security
Based of: Debian
Credentials: parrot:parrot
Homepage: https://www.parrotsec.org/
Info: Provides a huge arsenal of tools, utilities and libraries that IT and security professionals can use to test and assess the security of their assets in a reliable, compliant and reproducible way.
```
- [ ] Whonix - Added preparation
```
whonix
Pretty name: Whonix
Based of: Debian
Credentials: Unknown
Homepage: https://www.whonix.org/
Info: Superior Internet Privacy with Whonix™ As handy as an app - delivering maximum anonymity and security.
```

### Break changes:
- [x] list_csv and list_json arguments (bit) changed

### Changes:
- [x] Zorin 17 by @lj3954
- [x] list csv use | as delimiter
- [x] repair quickget indentation
- [x] removed whitespaces in quickget
- [x] changed tabs to spaces in quickget
- [x] Releases are sorted from latest to oldest
- [x] OS in alphabetical order

### Fix:
- [x] #864
- [x] #875
- [x] #883
- [x] #861 
- [x] wget2 by @lj3954
- [x] Download ISO for Windows & MacOS
- [x] Refactor arguments and help message

Include changes from @lj3954, @DaffyDuke and me

Also our two big updates will no longer be needed, everything is included here. 🥸 (hopefully) Check pls

### Mostly should work as expected.
Need more testing edge cases.
And finish download_iso_to

PS: Maybe I forgot mention some change...

Happy new year
🚀

### CODE REVIEW

**Comment by lj3954** [comment]
I feel like you're going off the rails with all these arguments. If someone's looking for the features of a distribution or what it's based on, they can get all that information from the website or through a quick search. The show-distro-homepage and open-distro-homepage do essentially the same thing. These arguments will just clutter the interface and overall make the UX worse. This kind of data should be just left to the list_csv function, in order to allow alternate UIs access to the information, if it's useful to them. 

It's almost as if you're just adding things for the sake of adding things, rather than trying to solve a problem (such as my commits mostly making under the hood improvements to downloads, especially for macOS and Windows, just to make the UX slightly better and fix a few small issues). It feels to be even more that way when you consider the branches you have with "operating systems" like Ventoy. That is a bootloader, it doesn't serve any purpose being in a VM unless you used it to implement a unique feature, say, automating the creation of one VM with multiple operating systems. And the whonix pull request you abandoned 3 months ago. That's an absolutely wonderful idea for an operating system to add, it would solve a very real problem and be extremely useful for countless people. But, you just left it there so you can instead add distros that nobody's heard of, just because it's not difficult to pull an ISO off sourceforge. Same with the idea presented by a few of different architectures. It's ambitious but would greatly improve the usefulness of this project, something that refactoring every function every month won't do. When I added the download-iso feature to a branch of mine, you immediately jumped over it and merged it into your branch, despite not seeming to at all care about my (much more major) changes that aren't directly user facing. I didn't add that because I'm trying to add every meaningless feature that an AI told me to, I added it because quickget hosts a large variety of operating systems (including many advanced functions which fetch the available releases directly from the web) and being able to download from that repository alongside verifying image integrity with just a single command is legitimately useful. 

You also need to be careful not to rush things. I can already see that you forgot to add Windows Server back to your new OS data array, and who knows what else might be missing or broken. So much testing must be done before merging such changes. For example, you implemented your new download-iso-to option for the macOS image downloading I worked on, but it doesn't work because of such a clear issue, I immediately spotted it while skimming over your commits. I pointed it out in a comment on your last PR, and in a review here; it's still not fixed, and you still marked the PR as ready for review. Any good program needs functionality to come first, and features to follow. Start your commit in the issues tab, not in the search engine. Adding features just to never look back (especially when your own features are being mentioned in issues) just isn't a good look. 

I don't feel right just being the bugfixer for all of your features. I don't want to focus on, instead of working on challenging undertakings, fixing the few obviously mistaken lines in your addition that should've never made it off your system. From now on when I work on this project, I'm not going to be reviewing your PRs and fixing these issues with the features I don't believe should even exist. I don't want you to create future PRs merging together my features, that aren't yet in the upstream project, with these changes I don't care for, even if they work correctly. I spent many hours over the course of over a week finding the best way I could re-implement the macrecovery python program within the quickget script, while making sure to fix every slight issue along the way. I'm not so happy to see it getting merged alongside broken code that the simplest of tests would reveal does not work, or missing some new features added in the same pull request. I never see fixes to your own features in your PRs, it's just new feature after new feature. What use will a user have for all these features that they know don't work half the time?

**Comment by zen0bit** [comment]
🤝 Mostly agree
👨🏽‍🔧 I am working on it..
🏷️ Nothing is abandoned!
👀 I am still fairly new to all this so.. (Not developer)
And where learn bash better than on some project which I like and use myself 😉
❤️ Comments even critical one are welcomed!

🪓 I can unmerge your PRs if you wish to...
⛑️ My bad. Sorry for marking PR as ready to soon. But I like green more then grey. (And didn't expect Wimpy be merging anything so soon)
😇

**Comment by lj3954** [comment]
Don't unmerge my changes, it'd break far more. My comment was probably significantly too harsh, it wasn't my intention, but that's just how I feel. It's better to have few, well-thought-out features that have few issues, rather than a bunch of features or changes that cause more pain than they're worth.

**Comment by philclifford** [comment]
Also it is much preferable to have individual PRs for distro additions and for individual feature additions or bug fixes.  It can be helpful sometimes to combine a set of pending PRs for a set of new distros (for example) or for a collection of pending fixes or new features. BUT you should leave maintainers the option of merging the individual PRs rather than closing them (so that for example the highly-desirable addition of Slint is not lost if this is closed rather than merged).  Far better to add lines to the description of the combined PR that close the individual PRs automatically.

Discrete PRs not only make review and testing easier, but also facilitate automation and maintenance.

**Comment by zen0bit** [comment]
Pushed latest changes

Still a lot of TODOs..

but os_info is here
Check it...

**Comment by zen0bit** [comment]
Almost done...

**Comment by zen0bit** [comment]
I heard all of you...
to @lj3954 
- Used less arguments
- Tried to don't clutter output to much
- Missed Windows Server etc. re added (hopefully everything, macos still needs to be solved)

to @philclifford
- Trying push bit harder.. (If not merged, I will re add separated PR)
- I need essential changes merged, since any inconsistency driving me crazy

**Comment by zen0bit** [comment]
Awaiting suggestions...
 meanwhile continuing work on whonix...

**Comment by lj3954** [comment]
Whonix should not be divided into gateway and workstation. Both are necessary, so it should download once and extract all the files. Then, both VMs must be automatically launched at the same time. It's completely pointless to add to quickemu otherwise, the entire point is for everything to automatically be set up and work.

**Comment by zen0bit** [comment]
> Whonix should not be divided into gateway and workstation.

> Both VMs must be automatically launched at the same time.

I though then workstation can be runned later (multiple times)

But I think we don't want to run more gateways..

Am I correct?

**Comment by zen0bit** [comment]
> Quickemu does not allow a VM to be launched twice at the same time.

It can recognise that two vms are same? I doubt

**Comment by TuxVinyards** [comment]
You are doing some really good work.  Your enthusiasm cannot be missed.

I think you are appreciating that a  lot of the above pieces of advice and the comments are sound, even if they are a bit harsh in places.

I look forward to integrating more of your URL info work into qqX, as I have already said to you elsewhere, and even if others are not so keen to see it.

My advice, much as above.  You do **_need to test your PR's more carefully_**.  I had to write code to check for the error that went through recently, the one where a URL check caused a directory to be created, for example.

I have also noticed that you are publishing a lot of work late at night / in the early hours.  Try to resist your enthusiasm.  Publish the next day, after you have slept and reflected on things. And after re-testing.

Also, do read the manual.

:rocket:

**Comment by zen0bit** [comment]
> Also, do read the manual.
 Which one? I have never ending list of manuals i have to read...
🚀

**Comment by lj3954** [comment]
> > Quickemu does not allow a VM to be launched twice at the same time.
> 
> It can recognise that two vms are same? I doubt
> 
> with two different configs and dir..
> 
> PS: just need to figured out how to create differently named (same name +1 ?) config (then os release edition) and fill dir structure appropriately
> 
> rest is done (not yet pushed) PS: But not yet tried guests..

Check what I've done on my whonix branch. It's not very clean and needs work (networking is the main thing that needs to be fixed), but you can definitely launch multiple **unique** VMs (different configs) from the same directory. My approach was to create a (fixed) whonix gateway config as a variable (if the guest OS is whonix) and pass it to another instance of quickemu via process substitution.

There's no need to create multiple directories. That would only be more difficult on the user, especially if you create 2 config files in the same folder.

**Comment by TuxVinyards** [comment]
@zen0bit  I just noticed that endeavouros  had a new release (Galileo) back in Nov,  and that it has quite a few radical changes, like change of desktop etc

Thought I would give you a  heads up on this one.  Probably take you all of ten minutes :rofl:   I could do it but you know the routine.  And then you would have to merge it into everything that you have done  here ....

**Comment by zen0bit** [comment]
> @zen0bit I just noticed that endeavouros had a new release (Galileo) back in Nov, and that it has quite a few radical changes, like change of desktop etc
> 
> Thought I would give you a heads up on this one. Probably take you all of ten minutes 🤣 I could do it but you know the routine. And then you would have to merge it into everything that you have done here ....

Here we go #907

**Comment by zen0bit** [comment]
Check pushed changes
I think good to go...
🥳

**Review by TuxVinyards — COMMENTED** [review]
I would like to think that one day the code will get tidied enough that we don't have to have all these shellcheck disablements. But if we don't turn off the hundreds of warnings, we can't see the errors, I suppose.   Hope's spring is eternal ....

**Comment by zen0bit** [comment]
https://github.com/oSoWoSo/quickemu/actions/runs/7555116912/job/20569381408

**Comment by TuxVinyards** [comment]
As a heads-up seemed okay, from the other day:   

I noticed that quickget Mageia is seriously out-of-date.   We are offering ver 8 which went EOL last month and is no longer downloadable ....  :roll_eyes:

**Comment by TuxVinyards** [comment]
I haven't really explored GitHub actions as a tool.   I have tended to see it as aimed more at enterprise level and left it be.  You seem to have done well with it and Mega Lint certainly looks impressive. 

There are so many tests.   Are all the languages that are being linted in use in quickemu?  Or are there snippets are hiding in places?

In general, I am a bit concerned about shellcheck being disabled left right and centre and then having claims made that the code is all good because it can now pass ....

Personally, I would feel happier knowing that the new code is being usage tested to see that it actually does what it is meant to do and that it can do it in different usage scenarios.

**Comment by zen0bit** [comment]
> I haven't really explored GitHub actions as a tool. I have tended to see it as aimed more at enterprise level and left it be. You seem to have done well with it and Mega Lint certainly looks impressive.
> 
> There are so many tests. Are all the languages that are being linted in use in quickemu? Or are there snippets are hiding in places?
> 
> In general, I am a bit concerned about shellcheck being disabled left right and centre and then having claims made that the code is all good because it can now pass ....
> 
> Personally, I would feel happier knowing that the new code is being usage tested to see that it actually does what it is meant to do and that it can do it in different usage scenarios.

I wanna use output of linters and create review on PR. But so far not succesfully.
Also megalinter show summary only on PRs from same repo 🥲 (At least for me now)

This will be closed, other PRs in progres..

**Pull request closed without merging**
