### PR TITLE
Added MX-Linux support

### PR DESCRIPTION
**Pull request by fridy1307**
Added support for MX-Linux (https://mxlinux.org/)
One quick question, Do I also need to add icons for list_csv? It is not written in quickget's guide to add new os, so I didn't add it.

### CODE REVIEW

**Comment by philclifford** [comment]
>  Do I also need to add icons for list_csv? It is not written in quickget's guide to add new os, so I didn't add it.
Best just to  give a [heads-up](https://github.com/quickemu-project/quickemu-icons/issues/12) to the icon project, and if possible supply a link to a suitable svg project logo.

**Comment by VPNMAHAWAR** [comment]
This is the url for the svg project logo: https://mxlinux.org/wp-content/uploads/2019/01/MX-Menu-icon-pyramids.svg

**Comment by daPhipz** [comment]
Thanks for the icon resource!
I'll have a look at implementing it in the coming days.

**Review by SwampRabbit — CHANGES_REQUESTED** [review]
Please use our official MX Linux download locations

https://sourceforge.net/projects/mx-linux/files/Final/Xfce/
https://sourceforge.net/projects/mx-linux/files/Final/KDE/
https://sourceforge.net/projects/mx-linux/files/Final/Fluxbox/
https://sourceforge.net/projects/mx-linux/files/Final/Xfce/ahs/

This has two benefits: 1) users know they are getting the official ISO  2) it helps us track the number of downloads

**Comment by philclifford** [comment]
Thanks @SwampRabbit 

I have updated to these in #322 and #324 and #334

> https://sourceforge.net/projects/mx-linux/files/Final/Xfce/
> https://sourceforge.net/projects/mx-linux/files/Final/KDE/
> https://sourceforge.net/projects/mx-linux/files/Final/Fluxbox/

This seems to show no files and is probably less important under QEmu anyway so have left it for now

> https://sourceforge.net/projects/mx-linux/files/Final/Xfce/ahs/

Cheers

**Comment by SwampRabbit** [comment]
@philclifford thank you very much, I actually pulled the PR and patched in the change the other day to test it.

quickget worked to pull the ISO and created a generic .conf

I'll be getting quickemu and quickgui into our (MX) repos in the coming days, I'm sure our users will like it.

**Comment by fridy1307** [comment]
Merged the PR :)

**Comment by flexiondotorg** [comment]
Merged via https://github.com/quickemu-project/quickemu/pull/322

**Pull request closed without merging**
