### PR TITLE
Add whonix

### LINKED ISSUE #740: Whonix Support?
Can we get Whonix support? I think that would be good because we have tails so whonix would also be good. This would also be good because Whonix takes some more steps then a one click install with a iso.

### PR DESCRIPTION
**Pull request by zen0bit**
Closes #740

Since whonix comes in 2 gcow2 images process slightly differ from others supported OSes (Which comes on ISOs)

- [x] Get images
- [x] Hash check
- [x] Upack images
- [x] Read license agreement
- [x] Accept/Decline license agreement
- [ ] Setup
- [ ] Run Whonix gateway
- [ ] Run Whonix workstation

Help appreciated

### CODE REVIEW

**Comment by zen0bit** [comment]
#767

**Comment by zen0bit** [comment]
whonix

**Comment by lj3954** [comment]
I've made some progress on this. Both VMs are now launched (output of the second VM should probably be piped to /dev/null). Internet connectivity must be fixed, though. 

https://github.com/lj3954/quickemu/tree/whonix-test

**Comment by ehula** [comment]
Whatever happened to this? It would be great to have.

**Pull request closed without merging**
