### PR TITLE
Add: quickfzf 0.23

### PR DESCRIPTION
**Pull request by zen0bit**
Quickemu and quickget GUI using fzf.

I just love your project and create this for my self, but if anyone find it useful, here it is...

quickfzf alias quickemu fzf user interface
https://www.youtube.com/embed/gJ5hqYEskOw

Enjoy
And give me feedback

### CODE REVIEW

**Comment by zen0bit** [comment]
Apology for fzf again, but I am still can't get quickgui working so...
flatter not my friend yet

**Comment by flexiondotorg** [comment]
This looks very interesting. I'll take a proper look before merging 😁

**Comment by zen0bit** [comment]
Small update
Tested with version 4.6

**Comment by zen0bit** [comment]
Windows leaved as is for now, waiting for downloading fix...

**Comment by zen0bit** [comment]
typo correction
Allow quickfzf to be run wherever the VMs are
raise version to 0.22

Thanks @philclifford

**Comment by zen0bit** [comment]
Added ability to edit VM's config files

**Pull request closed without merging**
